branch-defaults:
  master:
    environment: Demo-env-1
global:
  application_name: demo
  default_ec2_keyname: null
  default_platform: 64bit Amazon Linux 2017.09 v2.9.2 running Multi-container Docker 17.12.0-ce (Generic)
  default_region: us-east-1
  profile: eb-cli
  sc: git