branch-defaults:
  master:
    environment: Demo-env-2
global:
  application_name: demo
  default_ec2_keyname: ec2-key-pair-name
  default_platform: multi-container-docker-1.3.3-(generic)
  default_region: us-east-1
  profile: eb-cli
  sc: git