branch-defaults:
  master:
    environment: Demo-env-2
global:
  application_name: demo
  default_ec2_keyname: null
  default_platform: Docker 1.12.6
  default_region: us-east-1
  profile: eb-cli
  sc: git