branch-defaults:
  master:
    environment: docker-s4-project
global:
  application_name: docker-s4-project
  default_ec2_keyname: ec2-key-pair-name
  default_platform: multi-container-docker-1.3.3-(generic)
  default_region: eu-central-1
  profile: eb-cli
  sc: git