# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine: true
    steps:
      #check out code from githhub
      - checkout
      - run:
          name: Check Docker and Docker-compose versions
          command: |
            docker -v
            docker-compose -v
      - run:
          name: Run Docker
          command: docker-compose up --build -d
      - run:
          name: Check if Docker is running
          command: |
            docker images
            docker container ls
      #run tests!
      - run:
        name: Verify if docker container are responding via HTTP
        command: |
          curl --retry 10 --retry-delay 5 -v http://localhost:8000