# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine:
      services:
        - docker
    steps:
      - checkout
#      - run:
#          name: Show current branch
#          command: echo ${CIRCLE_BRANCH}
#      - run:
#          name: Docker info
#          command: docker info
      - run:
          name: Run Docker
          command: docker-compose up --build -d
#      - run:
#          name: Check if Docker is running
#          command: |
#            docker images
#            docker container ls
      - run:
          name: Verify if application is responding via HTTP
          command: |
            curl http://localhost:8000

#   test:
#      override:
#        -phpunit
  deploy:
    machine:
      services:
        - docker
    steps:
      - checkout
      - run:
          name: build and push Docker image
          command: |
            docker build -t internations/test ./php/
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push internations/test
#            TAG=0.1.$CIRCLE_BUILD_NUM
#            docker push internations/test:$TAG
#            docker login -u $DOCKER_USER -p $DOCKER_PASS
#            docker build -t internations/test:$TAG ./php/
#            cd ~/.docker
#            cat config.json
      - run:
          name: Install awscli
          command: |
            sudo apt-get update
            sudo apt-get install -y python-pip python-dev
            sudo pip install awsebcli --upgrade
      - run:
          name: Deploy to EB
          command: |
            bash ./.elasticbeanstalk/setup-eb.sh
            eb deploy -v Demo-${CIRCLE_BRANCH}
workflows:
  version: 2
  deploy-staging:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
#  deploy-production:
#    triggers:
#      - schedule:
#        cron: "0 * * * *"
#        filters:
#          branches:
#            only:
#              - master
#    jobs:
#      - build
#      - deploy:
#        requires:
#         - build