# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Check Docker and Docker-compose versions
          command: |
            docker -v
            docker-compose -v
      - run:
          name: Run Docker
          command: docker-compose up --build -d
      - run:
          name: Print folder content
          command: ls -a
      - run:
          name: PHP version
          command: php -v
      - run:
          name: Docker containers
          command: docker container ls

      #run tests!
      #- run: phpunit