# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Print folder content
          command: ls -a /var/www/html/
      - run:
          name: Check Docker and Docker-compose versions
          command: |
            docker -v
            docker-compose -v
      - run:
          name: Run Docker
          command: docker-compose up --build -d
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      #run tests!
      #- run: phpunit