# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine:
      services:
        - docker
    steps:
      #check out code from githhub
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Docker info
          command: docker info
      - run:
          name: Run Docker
          command: docker-compose up --build -d
      - run:
          name: Check if Docker is running
          command: |
            docker images
            docker container ls
      - run:
          name: Verify if application is responding via HTTP
          command: |
            curl http://localhost:8000

  #The deploy job
  deploy:
    machine:
      services:
        - docker
    steps:
        #check out code from githhub
        - checkout
        # Log the current branch
        - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
        - run:
          name: Deploying on AWS EB
          command: eb deploy

workflows:
    version: 2
    # The build and deploy workflow
    build_and_deploy:
        jobs:
            - build
            - deploy