# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine:
      services:
        - docker
    steps:
      - checkout
#      - run:
#          name: Show current branch
#          command: echo ${CIRCLE_BRANCH}
#      - run:
#          name: Docker info
#          command: docker info
#      - run:
#          name: Run Docker
#          command: docker-compose up --build -d
#      - run:
#          name: Check if Docker is running
#          command: |
#            docker images
#            docker container ls
#      - run:
#          name: Verify if application is responding via HTTP
#          command: |
#            curl http://localhost:8000
      - run:
          name: build and push Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t internations/test:$TAG ./php/
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push internations/test:$TAG

  deploy:
    machine:
      services:
        - docker
    steps:
      - checkout
      - run:
          name: Install awscli
          command: |
            sudo apt-get update
            sudo apt-get install -y python-pip python-dev
            sudo pip install awsebcli --upgrade
      - run:
          name: Deploy to EB
          command: |
            bash ./.elasticbeanstalk/setup-eb.sh
            eb deploy -v
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
#      - deploy:
#          filters:
#            branches:
#              only:
#                - master
#                - develop