# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine:
      services:
        - docker
    steps:
      #check out code from githhub
      - checkout
      # Log the current branch
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: Docker info
          command: docker info
      - run:
          name: Run Docker
          command: docker-compose up --build -d
      - run:
          name: Check if Docker is running
          command: |
            docker images
            docker container ls
      - run:
          name: Verify if application is responding via HTTP
          command: |
            curl http://localhost:8000

  deploy:
    machine:
      services:
        - docker
    steps:
      - checkout
      - run:
          name: Install awscli
          command: |
            sudo apt-get update
            sudo apt-get install -y python-pip python-dev
            sudo pip install awsebcli --upgrade
      - run:
          name: Deploy to EB if branch is Master
          command: |
            eb use Demo-env --profile default
            eb deploy -v --profile default
workflows:
  version: 2
  build-deploy:
    jobs:
#      - build
      - deploy:
          filters:
            branches:
              only:
                - master
#                - develop