# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine:
      services:
        - docker
    steps:
      #check out code from githhub
      - checkout
      - run:
          name: Docker info
          command: docker info
      - run:
          name: Install AWS CLI
          command: sudo pip install awsebcli --upgrade
      - run:
          name: Run Docker
          command: docker-compose up --build -d
      - run:
          name: Check if Docker is running
          command: |
            docker images
            docker container ls
      - run:
          name: Verify if application is responding via HTTP
          command: |
            curl http://localhost:8000

      - run:
          name: Deploying
          command: eb deploy master-docker-s4-project

workflows:
  version: 2
  build:
    jobs:
      - deploy:
        filters:
          branches:
            only:
              - staging
              - master