# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine: true
    steps:
      #check out code from githhub
      - checkout
      - run:
          name: Install aws cli
          command: pip install --upgrade awscli
      - run:
          name: Check Docker and Docker-compose versions
          command: |
            docker -v
            docker-compose -v
      - run:
          name: Run Docker
          command: docker-compose up --build -d
      - run:
          name: Check if Docker is running
          command: |
            docker images
            docker container ls
      - run:
          name: Verify if application is responding via HTTP
          command: |
            curl http://localhost:8000
    test:
      override:
        - ufo docker build
        - docker tag $(ufo docker image_name) hi_web

    deployment:
      staging:
        branch: master
        commands:
          - ufo ship hi-web --cluster stag --no-docker