# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine: true
    steps:
      #check out code from githhub
      - checkout
      - run:
        name: Check Docker and Docker-compose versions
        command: |
          docker -v
          docker-compose -v
      - run:
        name: Run Docker
        command: docker-compose up --build -d
      - run:
        name: Check if Docker is running
        command: |
          docker images
          docker container ls
      - run:
        name: Verify if application is responding via HTTP
        command: |
          curl http://localhost:8000
  deploy-job:
      docker:
        - image: my-image
      working_directory: /var/www/html
      steps:
        - run:
            name: Deploy to S3 if tests pass and branch is Master
            command: aws s3 sync jekyll/_site/docs s3://circle-production-static-site/docs/ --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master