# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine:
      services:
        - docker
    steps:
      #check out code from githhub
      - checkout
      - run:
          name: Docker info
          command: docker info
      - run:
          name: Run Docker
          command: docker-compose up --build -d
      - run:
          name: Check if Docker is running
          command: |
            docker images
            docker container ls
      - run:
          name: Verify if application is responding via HTTP
          command: |
            curl http://localhost:8000

deployment:
  staging:
    branch: master
    codedeploy:
      appname-1234:
        application_root: /
        region: us-east-1
        revision_location:
          revision_type: S3
          s3_location:
            bucket: my-bucket
            key_pattern: appname-1234-{BRANCH}-{SHORT_COMMIT}
        deployment_group: my-deployment-group