<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0Zzgo46\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0Zzgo46/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0Zzgo46.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0Zzgo46\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container0Zzgo46\srcDevDebugProjectContainer(array(
    'container.build_hash' => '0Zzgo46',
    'container.build_id' => '181555f9',
    'container.build_time' => 1522142680,
));
