<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNPnxkff\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNPnxkff/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerNPnxkff.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerNPnxkff\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerNPnxkff\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'NPnxkff',
    'container.build_id' => 'c501dc98',
    'container.build_time' => 1522229098,
));
