<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\TestController' shared autowired service.

include_once $this->targetDirs[3].'/src/Controller/TestController.php';

return $this->services['App\Controller\TestController'] = new \App\Controller\TestController();
